app = "discord-looper-bot"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "echo Deploy complete"

[processes]
  bot = "python bot.py"

[[services]]
  processes = ["bot"]   # <-- Asignamos quÃ© proceso usa este servicio
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080         # <-- Puerto dummy requerido por Fly

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50
